#!/bin/bash

set -euo pipefail

read -r bazel_version<.bazelversion
readonly bazel_platform="darwin"
readonly bazel_version_sha="eae082635743b753d2df6744bc2f4b7ed6af90c270769ff2f60cd6cebc4b7032"
readonly bazel_version_url="https://github.com/bazelbuild/bazel/releases/download/$bazel_version/bazel-$bazel_version-$bazel_platform-x86_64"
readonly script_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly bazel_root="$script_root/tmp/bazel/versions/$bazel_version-$bazel_platform"
readonly bazel_executable="$bazel_root/bin/bazel"

if [[ ! -x "$bazel_executable" ]]; then
  echo "Installing bazel..." >&2
  mkdir -p "$(dirname "$bazel_executable")"
  extra_curl_args=""
  if [[ -n "${BUILD_BUILDID:-}" ]]; then
    extra_curl_args="--silent"
  fi

  curl \
    --show-error \
    $extra_curl_args \
    --progress-bar \
    --retry 3 \
    --fail \
    --location \
    --output "$bazel_executable" \
    "$bazel_version_url"

  if echo "$bazel_version_sha  $bazel_executable" | shasum --check --status; then
    chmod +x "$bazel_executable"
  else
    echo "Bazel installer sha mismatch:" >&2
    shasum -a256 $bazel_executable | awk '{print $1;}' >&2
    rm -f "$bazel_executable"
    exit 1
  fi
fi

exec "$bazel_executable" "$@"